
BLENDER="C:\Program Files\Blender Foundation\Blender 3.3\blender.exe"
DIST=../dist

all : \
    $(DIST)/boss.pnct \
    $(DIST)/boss.scene \

$(DIST)/boss.scene : boss.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "boss.blend:Main" "$(DIST)/boss.scene"

$(DIST)/boss.pnct : boss.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "boss.blend:Main" "$(DIST)/boss.pnct" 
